
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.site.service.orders;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-10T16:12:30.870-03:00
 * Generated source version: 3.1.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "Orders",
                      portName = "OrdersSOAP",
                      targetNamespace = "http://www.site.com/service/Orders/",
                      wsdlLocation = "classpath:orders.wsdl",
                      endpointInterface = "com.site.service.orders.Orders")
                      
public class OrdersSOAPImpl implements Orders {

    private static final Logger LOG = Logger.getLogger(OrdersSOAPImpl.class.getName());

    /* (non-Javadoc)
     * @see com.site.service.orders.Orders#processOrderPlacement(com.site.schema.order.OrderInquiryType  orderInquiry )*
     */
    public com.site.schema.order.OrderInquiryResponseType processOrderPlacement(com.site.schema.order.OrderInquiryType orderInquiry) { 
        LOG.info("Executing operation processOrderPlacement");
        System.out.println(orderInquiry);
        try {
            com.site.schema.order.OrderInquiryResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
